---
- name: Build Dockerfile
  block:
    - name: Install pip3 on centos/RHEL
      ansible.builtin.yum:
        name: python3-pip
        state: present
      when: ansible_distribution in ["CentOS", "RedHat", "Rocky"]

    - name: Install pip3 on Debian/Ubuntu
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install pre-requisites python modules
      ansible.builtin.pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
          - docker

    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: "{{ role_path }}/files/Dockerfile"
        dest: /tmp/Dockerfile
        mode: "0644"

    - name: Build MlFlow Server Image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ tag }}"
        build:
          path: /tmp
        source: build
        state: present
